name: Docker Image CI

on:
  schedule:
    - cron: '0 12 1 * *'
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: |
              docker build . --file Dockerfile --tag cinerion/ciel-sbcl-voidlinux:$(date +%F)
              docker tag cinerion/ciel-sbcl-voidlinux:$(date +%F) cinerion/ciel-sbcl-voidlinux:latest
              docker push cinerion/ciel-sbcl-voidlinux
              docker push cinerion/ciel-sbcl-voidlinux:$(date +%F)
