name: Docker Image CI

on:
  schedule:
    - cron: '0 12 1 * *'
  push:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: |
              docker build . --file Dockerfile --tag cinerion/ciel-sbcl-voidlinux:$(date +%F)
              docker tag cinerion/ciel-sbcl-voidlinux:$(date +%F) cinerion/ciel-sbcl-voidlinux:latest
              docker push cinerion/ciel-sbcl-voidlinux
              docker push cinerion/ciel-sbcl-voidlinux:$(date +%F)
